-- 13_stage_fixture_expectations.sql
-- Stage fixture expectations into ops.fixture_expectations for reconcile.
-- Regenerated by legacy/fixtures/build_expectations.sh

CREATE TABLE IF NOT EXISTS edw_migration.ops.fixture_expectations (
  fixture_name STRING NOT NULL,
  target_table STRING NOT NULL,
  metric STRING NOT NULL,
  expected BIGINT,
  compare STRING NOT NULL,
  notes STRING,
  staged_at TIMESTAMP NOT NULL
) USING DELTA;

DELETE FROM edw_migration.ops.fixture_expectations;

INSERT INTO edw_migration.ops.fixture_expectations VALUES ('dim_city_snapshot', 'edw_migration.gold.mart_city_dimension', 'row_count', NULL, 'exact_when_expected_set', 'From dim_city_snapshot.csv', current_timestamp());
INSERT INTO edw_migration.ops.fixture_expectations VALUES ('dim_customer_after_migrate', 'edw_migration.gold.mart_customer_current', 'row_count', NULL, 'exact_when_expected_set', 'From dim_customer_after_migrate.csv (post Migrate*)', current_timestamp());
INSERT INTO edw_migration.ops.fixture_expectations VALUES ('dim_stock_item_after_migrate', 'edw_migration.gold.mart_stock_movements', 'row_count', NULL, 'exact_when_expected_set', 'From dim_stock_item_after_migrate.csv (post Migrate*)', current_timestamp());
INSERT INTO edw_migration.ops.fixture_expectations VALUES ('fact_sale_count', 'edw_migration.bronze.fact_sale', 'row_count', NULL, 'exact_when_expected_set', 'From fact_sale_count.csv', current_timestamp());
INSERT INTO edw_migration.ops.fixture_expectations VALUES ('sample_offline_city', 'edw_migration.gold.mart_city_dimension', 'row_count', 1, 'gte', 'Offline floor: city mart non-empty', current_timestamp());

SELECT * FROM edw_migration.ops.fixture_expectations ORDER BY fixture_name;
