#!/usr/bin/env bash
# ensure_source_alias_views.sh — space-free SQL Server views for Federation.
# Discovers TABLE_NAME LIKE '% %' from INFORMATION_SCHEMA (not a hardcoded list).
# One sqlcmd -Q per VIEW (do not batch CREATE without GO).
# Writes databricks/generated/02b_alias_probe.sql for the first alias (if any).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
if [ -f "${REPO_ROOT}/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  . "${REPO_ROOT}/.env" || true
  set +a
fi

ST="${SOURCE_TYPE:-sqlserver}"
if [ "$ST" != "sqlserver" ] && [ "$ST" != "azure_sql" ]; then
  echo "[alias_views] skip SOURCE_TYPE=${ST}"
  exit 0
fi

if ! command -v sqlcmd >/dev/null 2>&1; then
  echo "[alias_views] WARN sqlcmd missing — federation smoke may fail on spaced names" >&2
  exit 0
fi

SERVER="${AZ_SQL_HOST:-${SOURCE_HOST:-${AZ_SQL_SERVER:-}.database.windows.net}}"
USER="${AZ_SQL_ADMIN:-${SOURCE_USER:-}}"
PASS="${AZ_SQL_PASSWORD:-${SOURCE_PASSWORD:-}}"
DB="${AZ_SQL_DB:-${SOURCE_DATABASE:-}}"

if [ -z "$SERVER" ] || [ -z "$USER" ] || [ -z "$PASS" ] || [ -z "$DB" ]; then
  echo "[alias_views] WARN Azure SQL env incomplete; skip views" >&2
  exit 0
fi

echo "[alias_views] listing spaced TABLE_NAME on ${SERVER}/${DB}"
LIST="$(sqlcmd -S "$SERVER" -U "$USER" -P "$PASS" -d "$DB" -C -l 60 -h -1 -W -s $'\t' -Q \
  "SET NOCOUNT ON; SELECT TABLE_SCHEMA, TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE '% %' AND TABLE_TYPE = 'BASE TABLE';" \
  || true)"

mkdir -p "${REPO_ROOT}/databricks/generated"
FIRST_SCHEMA=""
FIRST_VIEW=""
COUNT=0
while IFS=$'\t' read -r schema name; do
  [ -z "${schema:-}" ] && continue
  case "$schema" in
    TABLE_SCHEMA|schema) continue ;;
  esac
  # skip sqlcmd noise
  case "$schema" in
    *rows*affected*|Changed*|---*) continue ;;
  esac
  view="${name// /}"
  if ! printf '%s' "$schema.$view" | grep -Eq '^[A-Za-z_][A-Za-z0-9_]*\.[A-Za-z_][A-Za-z0-9_]*$'; then
    echo "[alias_views] WARN skip unsafe ${schema}.${name} -> ${view}" >&2
    continue
  fi
  echo "[alias_views] CREATE OR ALTER VIEW ${schema}.${view} AS SELECT * FROM ${schema}.[${name}]"
  sqlcmd -S "$SERVER" -U "$USER" -P "$PASS" -d "$DB" -C -l 60 -Q \
    "CREATE OR ALTER VIEW ${schema}.${view} AS SELECT * FROM ${schema}.[${name}];"
  COUNT=$((COUNT + 1))
  if [ -z "$FIRST_VIEW" ]; then
    FIRST_SCHEMA="$schema"
    FIRST_VIEW="$view"
  fi
done <<<"$LIST"

if [ -n "$FIRST_VIEW" ]; then
  FED="${FOREIGN_CATALOG:-sqlserver_fed}"
  cat > "${REPO_ROOT}/databricks/generated/02b_alias_probe.sql" <<EOF
-- AUTO-GENERATED by ensure_source_alias_views.sh — first spaced-name alias
SELECT 'alias_probe_ok' AS check_name, COUNT(*) AS alias_rows
FROM ${FED}.${FIRST_SCHEMA}.${FIRST_VIEW};
EOF
  echo "[alias_views] wrote databricks/generated/02b_alias_probe.sql (${FIRST_SCHEMA}.${FIRST_VIEW})"
else
  rm -f "${REPO_ROOT}/databricks/generated/02b_alias_probe.sql"
  echo "[alias_views] no spaced table names"
fi
echo "[alias_views] done views=${COUNT}"
