#!/usr/bin/env python3
"""Generate bronze land + reconcile SQL and inventory INSERT from inventory.json."""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from slugify import backtick, slugify_ident  # noqa: E402


def load_env() -> None:
    env_path = ROOT / ".env"
    if not env_path.is_file():
        return
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


def emit_land(tables: list[dict], catalog: str, foreign: str) -> str:
    lines = [
        "-- AUTO-GENERATED by generate_from_inventory.py — do not edit by hand",
        f"-- catalog={catalog} foreign={foreign}",
        "DECLARE OR REPLACE VARIABLE v_batch_id STRING;",
        "DECLARE OR REPLACE VARIABLE v_started TIMESTAMP;",
        "SET VAR v_batch_id = 'bronze-all-' || date_format(current_timestamp(), 'yyyyMMddHHmmss');",
        "SET VAR v_started = current_timestamp();",
        "",
    ]
    for t in tables:
        if t.get("skip"):
            continue
        schema = t["source_schema"]
        name = t["source_name"]
        landing = t.get("landing_name") or slugify_ident(schema, name)
        src = f"{backtick(foreign)}.{backtick(schema)}.{backtick(name)}"
        dst = f"{backtick(catalog)}.bronze.{backtick(landing)}"
        sf = f"{backtick(catalog)}.source_fed.{backtick(landing)}"
        lines += [
            f"CREATE OR REPLACE VIEW {sf} AS SELECT * FROM {src};",
            f"CREATE OR REPLACE TABLE {dst}",
            "TBLPROPERTIES ('delta.columnMapping.mode' = 'name')",
            "AS",
            "SELECT",
            "  *,",
            "  current_timestamp() AS _bronze_loaded_at,",
            "  'azure_sql' AS _source_system,",
            "  v_batch_id AS _batch_id",
            f"FROM {sf};",
            f"INSERT INTO {backtick(catalog)}.ops.load_control "
            "(table_name, batch_id, row_count, started_at, ended_at, status)",
            f"SELECT 'bronze.{landing}', v_batch_id, COUNT(*), v_started, current_timestamp(), 'ok' FROM {dst};",
            "",
        ]
    lines.append(
        "SELECT 'bronze_land_all_ok' AS check_name, "
        f"(SELECT COUNT(*) FROM {backtick(catalog)}.information_schema.tables "
        f"WHERE table_schema = 'bronze') AS bronze_tables;"
    )
    return "\n".join(lines) + "\n"


def emit_reconcile(tables: list[dict], catalog: str, run_id: str) -> str:
    lines = [
        "-- AUTO-GENERATED reconcile: bronze vs source_fed row counts",
        f"-- run_id={run_id}",
        f"DELETE FROM {backtick(catalog)}.ops.reconcile_results WHERE run_id = '{run_id}' "
        "AND check_id LIKE 'bronze_vs_source:%';",
        "",
    ]
    for t in tables:
        if t.get("skip"):
            continue
        landing = t.get("landing_name") or slugify_ident(t["source_schema"], t["source_name"])
        bronze = f"{backtick(catalog)}.bronze.{backtick(landing)}"
        source = f"{backtick(catalog)}.source_fed.{backtick(landing)}"
        cid = f"bronze_vs_source:{landing}"
        lines += [
            f"INSERT INTO {backtick(catalog)}.ops.reconcile_results",
            "  (check_id, table_name, expected, actual, delta, result, run_id, ts)",
            "SELECT",
            f"  '{cid}',",
            f"  'bronze.{landing}',",
            f"  CAST((SELECT COUNT(*) FROM {source}) AS STRING),",
            f"  CAST((SELECT COUNT(*) FROM {bronze}) AS STRING),",
            f"  CAST((SELECT COUNT(*) FROM {source}) - (SELECT COUNT(*) FROM {bronze}) AS STRING),",
            f"  CASE WHEN (SELECT COUNT(*) FROM {source}) = (SELECT COUNT(*) FROM {bronze}) "
            "THEN 'pass' ELSE 'fail' END,",
            f"  '{run_id}',",
            "  current_timestamp();",
            "",
        ]
    lines.append(
        f"SELECT check_id, result FROM {backtick(catalog)}.ops.reconcile_results "
        f"WHERE run_id = '{run_id}' ORDER BY check_id;"
    )
    return "\n".join(lines) + "\n"


def emit_inventory_sql(inv: dict, catalog: str) -> str:
    run_id = inv["run_id"]
    lines = [
        f"DELETE FROM {backtick(catalog)}.ops.migration_inventory WHERE run_id = '{run_id}' OR run_id IS NULL;",
    ]
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    for t in inv.get("tables", []):
        landing = t.get("landing_name") or ""
        skip = "true" if t.get("skip") else "false"
        reason = (t.get("skip_reason") or "").replace("'", "''")
        lines.append(
            f"INSERT INTO {backtick(catalog)}.ops.migration_inventory "
            "(run_id, object_type, source_schema, source_name, landing_name, skip, skip_reason, discovered_at) "
            f"VALUES ('{run_id}', 'table', '{t['source_schema'].replace(chr(39), chr(39)+chr(39))}', "
            f"'{t['source_name'].replace(chr(39), chr(39)+chr(39))}', '{landing}', {skip}, "
            f"{('NULL' if not reason else chr(39)+reason+chr(39))}, TIMESTAMP'{now}');"
        )
    for p in inv.get("procs", []):
        skip = "true" if p.get("skip") else "false"
        reason = (p.get("skip_reason") or "").replace("'", "''")
        lines.append(
            f"INSERT INTO {backtick(catalog)}.ops.migration_inventory "
            "(run_id, object_type, source_schema, source_name, landing_name, skip, skip_reason, discovered_at) "
            f"VALUES ('{run_id}', 'proc', '{p['source_schema'].replace(chr(39), chr(39)+chr(39))}', "
            f"'{p['source_name'].replace(chr(39), chr(39)+chr(39))}', NULL, {skip}, "
            f"{('NULL' if not reason else chr(39)+reason+chr(39))}, TIMESTAMP'{now}');"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    load_env()
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-id", required=True)
    ap.add_argument("--catalog", default=os.environ.get("DATABRICKS_CATALOG", "edw_migration"))
    ap.add_argument("--foreign-catalog", default=os.environ.get("FOREIGN_CATALOG", "wwi_dw_fed"))
    args = ap.parse_args()

    inv_path = ROOT / "agents" / "out" / args.run_id / "inventory.json"
    if not inv_path.is_file():
        print(f"missing {inv_path} — run discover_inventory.py first", file=sys.stderr)
        return 1
    inv = json.loads(inv_path.read_text())
    tables = inv.get("tables", [])

    gen = ROOT / "databricks" / "generated"
    gen.mkdir(parents=True, exist_ok=True)
    (gen / "10_land_all.sql").write_text(emit_land(tables, args.catalog, args.foreign_catalog))
    (gen / "reconcile.sql").write_text(emit_reconcile(tables, args.catalog, args.run_id))
    (gen / "load_inventory.sql").write_text(emit_inventory_sql(inv, args.catalog))
    # Keep placeholder templates with __UC_CATALOG__ for render by rewriting land with placeholders
    land_tmpl = emit_land(tables, "__UC_CATALOG__", "__FOREIGN_CATALOG__")
    (gen / "10_land_all.sql").write_text(land_tmpl)
    (gen / "reconcile.sql").write_text(emit_reconcile(tables, "__UC_CATALOG__", args.run_id))
    (gen / "load_inventory.sql").write_text(emit_inventory_sql(inv, "__UC_CATALOG__"))

    print(f"[generate] wrote {gen}/10_land_all.sql, reconcile.sql, load_inventory.sql ({len(tables)} tables)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
