#!/usr/bin/env bash
# Materialize .env for the guided demo from az + Databricks CLI sessions.
# User must already have run: az login && databricks auth login (or set PAT).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"

need() { command -v "$1" >/dev/null 2>&1 || { echo "missing tool: $1" >&2; exit 1; }; }
need az
need databricks
need python3
need openssl

if ! az account show >/dev/null 2>&1; then
  echo "Azure not logged in. Run: az login" >&2
  exit 1
fi

SUB="$(az account show --query id -o tsv)"
LOC="${AZ_LOCATION:-eastus}"
RG="${AZ_RG:-rg-edw-migration-demo}"
SUFFIX="$(openssl rand -hex 3)"
SQL_SERVER="${AZ_SQL_SERVER:-sql-edwmig-${SUFFIX}}"
SQL_ADMIN="${AZ_SQL_ADMIN:-edwadmin}"
SQL_PASSWORD="${AZ_SQL_PASSWORD:-}"
if [ -z "$SQL_PASSWORD" ]; then
  SQL_PASSWORD="Edw$(openssl rand -base64 18 | tr -dc 'A-Za-z0-9' | head -c 20)!"
fi
SQL_DB="${AZ_SQL_DB:-WideWorldImportersDW}"

HOST="${DATABRICKS_HOST:-}"
if [ -z "$HOST" ]; then
  HOST="$(databricks auth env --output json 2>/dev/null | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("DATABRICKS_HOST") or d.get("host") or "")' 2>/dev/null || true)"
fi
if [ -z "$HOST" ]; then
  HOST="$(python3 - <<'PY'
import configparser, os
p=os.path.expanduser("~/.databrickscfg")
c=configparser.ConfigParser()
c.read(p)
for sec in c.sections():
    if c.has_option(sec,"host"):
        print(c.get(sec,"host")); break
PY
)"
fi
if [ -z "$HOST" ]; then
  echo "DATABRICKS_HOST unknown. Run: databricks auth login --host <workspace-url>" >&2
  exit 1
fi

WH="${DATABRICKS_WAREHOUSE_ID:-}"
if [ -z "$WH" ]; then
  WH="$(databricks warehouses list -o json 2>/dev/null | python3 -c '
import json,sys
rows=json.load(sys.stdin)
# prefer serverless / running
for r in rows:
    if str(r.get("enable_serverless_compute", True)) and r.get("state") in (None,"RUNNING","STARTING","STOPPED"):
        print(r["id"]); break
else:
    print(rows[0]["id"] if rows else "")
' 2>/dev/null || true)"
fi
if [ -z "$WH" ]; then
  echo "No SQL warehouse found. Create a serverless warehouse then re-run." >&2
  exit 1
fi

CATALOG="${DATABRICKS_CATALOG:-edw_migration}"
SCOPE="${DATABRICKS_SECRET_SCOPE:-edw-migration}"
TOKEN_LINE=""
if [ -n "${DATABRICKS_TOKEN:-}" ]; then
  TOKEN_LINE="DATABRICKS_TOKEN=${DATABRICKS_TOKEN}"
fi

umask 077
cat >"$ENV_FILE" <<EOF
# Generated by agents/tools/materialize_demo_env.sh — do not commit
SOURCE_TYPE=sqlserver
SOURCE_HOST=${SQL_SERVER}.database.windows.net
SOURCE_PORT=1433
SOURCE_DATABASE=${SQL_DB}
SOURCE_USER=${SQL_ADMIN}
SOURCE_PASSWORD=${SQL_PASSWORD}
AZ_SUBSCRIPTION_ID=${SUB}
AZ_LOCATION=${LOC}
AZ_RG=${RG}
AZ_SQL_SERVER=${SQL_SERVER}
AZ_SQL_ADMIN=${SQL_ADMIN}
AZ_SQL_PASSWORD=${SQL_PASSWORD}
AZ_SQL_DB=${SQL_DB}
AZ_SQL_HOST=${SQL_SERVER}.database.windows.net
DATABRICKS_HOST=${HOST}
${TOKEN_LINE}
DATABRICKS_WAREHOUSE_ID=${WH}
DATABRICKS_CATALOG=${CATALOG}
DATABRICKS_SECRET_SCOPE=${SCOPE}
FOREIGN_CATALOG=wwi_dw_fed
CONNECTION_NAME=azure_sql_edw
EOF

echo "[materialize_demo_env] wrote ${ENV_FILE}"
echo "[materialize_demo_env] subscription=${SUB} server=${SQL_SERVER} catalog=${CATALOG} warehouse=${WH}"
echo "[materialize_demo_env] Next: make bootstrap && make setup  (or launch edw-demo-guide)"
