#!/usr/bin/env bash
# build_expectations.sh — regenerate expectations.json from exported CSV fixtures.
# Counts data rows (total lines minus 1 header). Writes legacy/fixtures/expectations.json.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${SCRIPT_DIR}/expectations.json"

count_rows() {
  local f="$1"
  if [ ! -f "$f" ]; then echo ""; return; fi
  local n
  n="$(wc -l < "$f" | tr -d ' ')"
  if [ "$n" -le 1 ]; then echo 0; else echo $((n - 1)); fi
}

CITY="$(count_rows "${SCRIPT_DIR}/dim_city_snapshot.csv")"
CUST="$(count_rows "${SCRIPT_DIR}/dim_customer_after_migrate.csv")"
STOCK="$(count_rows "${SCRIPT_DIR}/dim_stock_item_after_migrate.csv")"
FACT="$(count_rows "${SCRIPT_DIR}/fact_sale_count.csv")"
# fact_sale_count.csv may be a single-row aggregate; if so use its value
if [ -f "${SCRIPT_DIR}/fact_sale_count.csv" ]; then
  VAL="$(tail -n +2 "${SCRIPT_DIR}/fact_sale_count.csv" | head -1 | tr -d '[:space:],' || true)"
  if [[ "$VAL" =~ ^[0-9]+$ ]]; then FACT="$VAL"; fi
fi

python3 - "$OUT" "${CITY:-}" "${CUST:-}" "${STOCK:-}" "${FACT:-}" <<'PY'
import json, sys
out, city, cust, stock, fact = sys.argv[1:6]

def num(x):
    return int(x) if x not in ("", None) else None

expectations = [
  {
    "fixture_name": "dim_city_snapshot",
    "target_table": "edw_migration.gold.mart_city_dimension",
    "metric": "row_count",
    "expected": num(city),
    "compare": "exact_when_expected_set",
    "notes": "From dim_city_snapshot.csv",
  },
  {
    "fixture_name": "dim_customer_after_migrate",
    "target_table": "edw_migration.gold.mart_customer_current",
    "metric": "row_count",
    "expected": num(cust),
    "compare": "exact_when_expected_set",
    "notes": "From dim_customer_after_migrate.csv (post Migrate*)",
  },
  {
    "fixture_name": "dim_stock_item_after_migrate",
    "target_table": "edw_migration.gold.mart_stock_movements",
    "metric": "row_count",
    "expected": num(stock),
    "compare": "exact_when_expected_set",
    "notes": "From dim_stock_item_after_migrate.csv (post Migrate*)",
  },
  {
    "fixture_name": "fact_sale_count",
    "target_table": "edw_migration.bronze.fact_sale",
    "metric": "row_count",
    "expected": num(fact),
    "compare": "exact_when_expected_set",
    "notes": "From fact_sale_count.csv",
  },
  {
    "fixture_name": "sample_offline_city",
    "target_table": "edw_migration.gold.mart_city_dimension",
    "metric": "row_count",
    "expected": 1,
    "compare": "gte",
    "notes": "Offline floor: city mart non-empty",
  },
]
doc = {"version": 1, "description": "Generated by build_expectations.sh", "expectations": expectations}
with open(out, "w") as f:
    json.dump(doc, f, indent=2)
    f.write("\n")
print(f"wrote {out}")
PY

# Also emit a Databricks SQL seed file for staging
python3 - "$OUT" "${SCRIPT_DIR}/../.." <<'PY'
import json, sys
from pathlib import Path
doc = json.loads(Path(sys.argv[1]).read_text())
repo = Path(sys.argv[2])
sql_path = repo / "databricks/tests/13_stage_fixture_expectations.sql"
lines = [
  "-- 13_stage_fixture_expectations.sql",
  "-- Stage fixture expectations into ops.fixture_expectations for reconcile.",
  "-- Regenerated by legacy/fixtures/build_expectations.sh",
  "",
  "CREATE TABLE IF NOT EXISTS edw_migration.ops.fixture_expectations (",
  "  fixture_name STRING NOT NULL,",
  "  target_table STRING NOT NULL,",
  "  metric STRING NOT NULL,",
  "  expected BIGINT,",
  "  compare STRING NOT NULL,",
  "  notes STRING,",
  "  staged_at TIMESTAMP NOT NULL",
  ") USING DELTA;",
  "",
  "DELETE FROM edw_migration.ops.fixture_expectations;",
  "",
]
for e in doc["expectations"]:
    exp = "NULL" if e.get("expected") is None else str(int(e["expected"]))
    notes = (e.get("notes") or "").replace("'", "''")
    lines.append(
        "INSERT INTO edw_migration.ops.fixture_expectations VALUES ("
        f"'{e['fixture_name']}', '{e['target_table']}', '{e['metric']}', "
        f"{exp}, '{e['compare']}', '{notes}', current_timestamp());"
    )
lines += ["", "SELECT * FROM edw_migration.ops.fixture_expectations ORDER BY fixture_name;", ""]
sql_path.write_text("\n".join(lines))
print(f"wrote {sql_path}")
PY

echo "[build_expectations] done."
